name: schedule-bonus

on: [pull_request, push, workflow_dispatch]

jobs:
  schedule-bonus:
    runs-on: ubuntu-latest
    env:
      path: homework/schedule/build
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: Compile
      working-directory: ${{ env.path }}
      run: |
        cmake ..
        make
    - name: Run tests
      working-directory: ${{ env.path }}
      run: ./schedule-ut-bonus
